# Todo App
apiVersion: v1
kind: Secret
metadata:
  name: todo-app
type: Opaque
stringData:
  secretKey: (enter a secret key)
  databaseURI: mysql+pymysql://root:(root password)@mysql/(database name)
---
# MySQL
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
stringData:
  rootPassword: (enter a root password)
  database: (enter the name of the database)